TRUNCATE TABLE dbo.NO
TRUNCATE TABLE dbo.[CHECK]
TRUNCATE TABLE dbo.[FOREIGN_COMPANY]
TRUNCATE TABLE dbo.[MAKE]
TRUNCATE TABLE dbo.[READY_DOCUMENTS]
TRUNCATE TABLE dbo.[STANDARD1]
TRUNCATE TABLE dbo.[STANDARD2]
TRUNCATE TABLE dbo.[TAKEN]
